//
//  AchievementDefinitions.swift
//  Fitglide_ios
//
//  Created by Sandip Tiwari on 19/07/25.
//

import Foundation

// MARK: - Achievement Definitions
struct AchievementDefinitions {
    static let allAchievements: [Achievement] = [
        // Level 1: Shuruaat (Beginning) - 3 achievements required
        Achievement(
            id: "first_steps",
            title: "First Steps",
            description: "Complete your first 1,000 steps",
            icon: "figure.walk",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1000,
            level: 1,
            fitCoinsReward: 25,
            badgeImageName: "Bhaag Bhaukali",
            isHidden: false,
            unlockCondition: "Reach 1,000 steps in a day"
        ),
        Achievement(
            id: "first_workout",
            title: "First Workout",
            description: "Complete your first workout",
            icon: "figure.run",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 1,
            fitCoinsReward: 50,
            badgeImageName: "Toofani Mode ON",
            isHidden: false,
            unlockCondition: "Complete any workout"
        ),
        Achievement(
            id: "three_day_streak",
            title: "3-Day Streak",
            description: "Maintain a 3-day workout streak",
            icon: "flame.fill",
            category: .streak,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 3,
            level: 1,
            fitCoinsReward: 75,
            badgeImageName: "Lagataar Legend",
            isHidden: false,
            unlockCondition: "Workout for 3 consecutive days"
        ),
        
        // Level 2: Josh (Enthusiasm) - 6 achievements required
        Achievement(
            id: "step_master",
            title: "Step Master",
            description: "Reach 10,000 steps in a day",
            icon: "figure.run",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 10000,
            level: 2,
            fitCoinsReward: 100,
            badgeImageName: "Speed Demon",
            isHidden: false,
            unlockCondition: "Reach 10,000 steps in a day"
        ),
        Achievement(
            id: "week_warrior",
            title: "Week Warrior",
            description: "Maintain a 7-day step streak",
            icon: "flame.fill",
            category: .streak,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 7,
            level: 2,
            fitCoinsReward: 150,
            badgeImageName: "Hafta Warrior",
            isHidden: false,
            unlockCondition: "Workout for 7 consecutive days"
        ),
        Achievement(
            id: "first_run",
            title: "First Run",
            description: "Complete your first running workout",
            icon: "figure.run",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 2,
            fitCoinsReward: 100,
            badgeImageName: "Daud Ka Raja",
            isHidden: false,
            unlockCondition: "Complete a running workout"
        ),
        Achievement(
            id: "meal_tracker",
            title: "Meal Tracker",
            description: "Log your first meal",
            icon: "fork.knife",
            category: .nutrition,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 2,
            fitCoinsReward: 50,
            badgeImageName: "Thali Tandoor",
            isHidden: false,
            unlockCondition: "Log your first meal"
        ),
        Achievement(
            id: "social_butterfly",
            title: "Social Butterfly",
            description: "Add your first friend",
            icon: "person.2.fill",
            category: .social,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 2,
            fitCoinsReward: 75,
            badgeImageName: "Max ka Dost",
            isHidden: false,
            unlockCondition: "Add your first friend"
        ),
        Achievement(
            id: "team_player",
            title: "Team Player",
            description: "Join your first pack",
            icon: "person.3.fill",
            category: .social,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 2,
            fitCoinsReward: 75,
            badgeImageName: "Pack Leader",
            isHidden: false,
            unlockCondition: "Join your first pack"
        ),
        
        // Level 3: Jazba (Passion) - 10 achievements required
        Achievement(
            id: "month_master",
            title: "Month Master",
            description: "Maintain a 30-day step streak",
            icon: "calendar",
            category: .streak,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 30,
            level: 3,
            fitCoinsReward: 500,
            badgeImageName: "Mahina Master",
            isHidden: false,
            unlockCondition: "Workout for 30 consecutive days"
        ),
        Achievement(
            id: "distance_diva",
            title: "Distance Diva",
            description: "Run 10 kilometers in a single workout",
            icon: "figure.run",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 10,
            level: 3,
            fitCoinsReward: 300,
            badgeImageName: "Distance Diva",
            isHidden: false,
            unlockCondition: "Run 10km in one workout"
        ),
        Achievement(
            id: "century_club",
            title: "Century Club",
            description: "Complete 100 workouts",
            icon: "trophy.fill",
            category: .milestone,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 100,
            level: 3,
            fitCoinsReward: 400,
            badgeImageName: "Century Club",
            isHidden: false,
            unlockCondition: "Complete 100 workouts"
        ),
        Achievement(
            id: "sleep_well",
            title: "Sleep Well",
            description: "Get 8 hours of sleep",
            icon: "bed.double.fill",
            category: .wellness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 8,
            level: 3,
            fitCoinsReward: 100,
            badgeImageName: "Neend Ninja",
            isHidden: false,
            unlockCondition: "Sleep for 8 hours"
        ),
        Achievement(
            id: "water_champion",
            title: "Water Champion",
            description: "Drink 2.5L of water in a day",
            icon: "drop.fill",
            category: .wellness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 2.5,
            level: 3,
            fitCoinsReward: 100,
            badgeImageName: "Paani Piyakkad",
            isHidden: false,
            unlockCondition: "Drink 2.5L of water"
        ),
        Achievement(
            id: "nutrition_expert",
            title: "Nutrition Expert",
            description: "Log 50 meals",
            icon: "leaf.fill",
            category: .nutrition,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 50,
            level: 3,
            fitCoinsReward: 200,
            badgeImageName: "Nutrition Guru",
            isHidden: false,
            unlockCondition: "Log 50 meals"
        ),
        Achievement(
            id: "first_challenge",
            title: "Challenge Accepted",
            description: "Participate in your first challenge",
            icon: "trophy.fill",
            category: .challenge,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 3,
            fitCoinsReward: 150,
            badgeImageName: "Challenge Champion",
            isHidden: false,
            unlockCondition: "Join your first challenge"
        ),
        Achievement(
            id: "zen_beast",
            title: "Zen Beast",
            description: "Achieve stress-free zone for 7 days",
            icon: "brain.head.profile",
            category: .wellness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 7,
            level: 3,
            fitCoinsReward: 200,
            badgeImageName: "Zen Beast",
            isHidden: false,
            unlockCondition: "Maintain low stress for 7 days"
        ),
        Achievement(
            id: "cycling_complete",
            title: "Cycling Complete",
            description: "Complete your first cycling workout",
            icon: "bicycle",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 3,
            fitCoinsReward: 150,
            badgeImageName: "Pedal Powerhouse",
            isHidden: false,
            unlockCondition: "Complete a cycling workout"
        ),
        Achievement(
            id: "all_meals_logged",
            title: "All Meals Logged",
            description: "Log all meals for a week",
            icon: "fork.knife",
            category: .nutrition,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 21, // 3 meals x 7 days
            level: 3,
            fitCoinsReward: 250,
            badgeImageName: "Meal Master",
            isHidden: false,
            unlockCondition: "Log all meals for 7 days"
        ),
        
        // Level 4: Shakti (Power) - 15 achievements required
        Achievement(
            id: "hundred_day_streak",
            title: "100-Day Streak",
            description: "Maintain a 100-day workout streak",
            icon: "flame.fill",
            category: .streak,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 100,
            level: 4,
            fitCoinsReward: 1000,
            badgeImageName: "Sau Din Saath",
            isHidden: false,
            unlockCondition: "Workout for 100 consecutive days"
        ),
        Achievement(
            id: "marathon_walker",
            title: "Marathon Walker",
            description: "Walk 42,195 steps in a day",
            icon: "figure.hiking",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 42195,
            level: 4,
            fitCoinsReward: 800,
            badgeImageName: "Daud Ka Maharaja",
            isHidden: false,
            unlockCondition: "Walk 42,195 steps in a day"
        ),
        Achievement(
            id: "pack_leader",
            title: "Pack Leader",
            description: "Create and lead a pack",
            icon: "person.3.fill",
            category: .social,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 4,
            fitCoinsReward: 300,
            badgeImageName: "Pack Captain",
            isHidden: false,
            unlockCondition: "Create and lead a pack"
        ),
        Achievement(
            id: "challenge_winner",
            title: "Challenge Winner",
            description: "Win your first challenge",
            icon: "trophy.fill",
            category: .challenge,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 4,
            fitCoinsReward: 500,
            badgeImageName: "Challenge Victor",
            isHidden: false,
            unlockCondition: "Win a challenge"
        ),
        Achievement(
            id: "all_goals_achieved",
            title: "All Goals Achieved",
            description: "Achieve all daily goals for a week",
            icon: "checkmark.circle.fill",
            category: .milestone,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 7,
            level: 4,
            fitCoinsReward: 400,
            badgeImageName: "Full Josh Mode",
            isHidden: false,
            unlockCondition: "Achieve all daily goals for 7 days"
        ),
        
        // Level 5: Moksha (Enlightenment) - 20 achievements required
        Achievement(
            id: "year_warrior",
            title: "Year Warrior",
            description: "Maintain a 365-day workout streak",
            icon: "calendar",
            category: .streak,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 365,
            level: 5,
            fitCoinsReward: 5000,
            badgeImageName: "Saal Ka Saathi",
            isHidden: false,
            unlockCondition: "Workout for 365 consecutive days"
        ),
        Achievement(
            id: "ultra_marathon",
            title: "Ultra Marathon",
            description: "Complete an ultra marathon distance",
            icon: "figure.run",
            category: .fitness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 50, // 50km
            level: 5,
            fitCoinsReward: 2000,
            badgeImageName: "Ultra Legend",
            isHidden: false,
            unlockCondition: "Run 50km in one workout"
        ),
        Achievement(
            id: "community_champion",
            title: "Community Champion",
            description: "Help 100 people achieve their goals",
            icon: "heart.fill",
            category: .social,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 100,
            level: 5,
            fitCoinsReward: 1000,
            badgeImageName: "Community Hero",
            isHidden: false,
            unlockCondition: "Help 100 people achieve goals"
        ),
        Achievement(
            id: "fitness_guru",
            title: "Fitness Guru",
            description: "Complete 500 workouts",
            icon: "brain.head.profile",
            category: .milestone,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 500,
            level: 5,
            fitCoinsReward: 1500,
            badgeImageName: "Fitness Guru",
            isHidden: false,
            unlockCondition: "Complete 500 workouts"
        ),
        Achievement(
            id: "zen_master",
            title: "Zen Master",
            description: "Achieve perfect wellness for 30 days",
            icon: "brain.head.profile",
            category: .wellness,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 30,
            level: 5,
            fitCoinsReward: 1000,
            badgeImageName: "Zen Master",
            isHidden: false,
            unlockCondition: "Perfect wellness for 30 days"
        ),
        Achievement(
            id: "legendary_achiever",
            title: "Legendary Achiever",
            description: "Unlock all achievements",
            icon: "crown.fill",
            category: .milestone,
            isUnlocked: false,
            unlockedDate: nil,
            progress: nil,
            target: 1,
            level: 5,
            fitCoinsReward: 10000,
            badgeImageName: "Legendary",
            isHidden: true,
            unlockCondition: "Unlock all other achievements"
        )
    ]
}
